version: "3"
services:
  springweb:
    image: "supawer0728/graphql-spring-web"
    ports:
      - "8080:8080"
    environment:
      - "SPRING_PROFILES_ACTIVE=docker"
    depends_on:
      - mongodb
  mongodb:
    image: "mongo:4.2.3"
    ports:
      - "27017"